spring:
  application:
    name: cloud-config-server
config:
  property: Don't change your mind
eureka:
  instance:
    prefer-ip-address: true
    
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:5000/eureka
